# You can find more information about each property here: https://github.com/kristofk/podcast-template/wiki/Podcast-properties

# Channel properties
title: Running with Problems
description: A podcast about the running and the lives of runners. RSSVERIFY
author: Mildly Athletic Couple
language: en
category: "Health &amp; Fitness"

itunesExplicit: yes
imageURL: https://episodes.runningwithproblems.run/logo_3000x3000.png
itunesImage: https://episodes.runningwithproblems.run/logo_3000x3000.png
itunesAuthor: Mildly Athletic Couple
itunesCategory: "Health &amp; Fitness"

# Podcast Namespace Tags
podcast:
  locked: yes
  updateFrequency:
    name: Biweekly
    rrule: "FREQ=WEEKLY;INTERVAL=2"

# Other info
email: podcast@runningwithproblems.run
itunesOwnerEmail: podcast@runningwithproblems.run
itunesOwnerName: Miranda Williamson and Jon Eisen
itunesType: episodic

itunesCategoryTags: |
  <itunes:category text="Health &amp; Fitness">
    <itunes:category text="Fitness"/>
    <itunes:category text="Mental Health"/>
  </itunes:category>

# Jekyll properties
baseurl:
url: https://runningwithproblems.run

# Build settings (only touch this if you know what you are doing)
permalink: /episodes/:slug
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
