# You can find more information about each property here: https://github.com/kristofk/podcast-template/wiki/Podcast-properties

# Channel properties
title: Running with Problems
description: A podcast about the challenges we face as runners, from navigating our bodies, dealing with social dynamics, and facing personal trauma
author: Mildly Athletic Couple
language: en
category: "Health &amp; Fitness"

itunesExplicit: yes
imageURL: https://res.cloudinary.com/dm9zyeqzp/image/upload/v1682385897/cover_rblshc.png
itunesImage: https://res.cloudinary.com/dm9zyeqzp/image/upload/v1682385897/cover_rblshc.png
itunesAuthor: Mildly Athletic Couple
itunesCategory: "Health &amp; Fitness"

# Other info
email: podcast@runningwithproblems.run
itunesOwnerEmail: podcast@runningwithproblems.run
itunesOwnerName: Miranda Williamson and Jon Eisen
itunesType: episodic

itunesCategoryTags: |
  <itunes:category text="Health &amp; Fitness">
    <itunes:category text="Fitness"/>
    <itunes:category text="Mental Health"/>
  </itunes:category>

# Jekyll properties
baseurl:
url: https://runningwithproblems.run

# Build settings (only touch this if you know what you are doing)
permalink: /episodes/:slug
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
