# You can find more information about each property here: https://github.com/kristofk/podcast-template/wiki/Podcast-properties

# Channel properties
title: Running with Problems
description: A podcast about runners, running, and relationships.
author: Miranda Williamson and Jon Eisen.
language: English
category: running
imageURL: https://runningwithproblems.run/img/cover.png
itunesExplicit: yes

# Other info
email: sweet1miranda@hotmail.com

# Jekyll properties
baseurl: runningwithproblems.run
url: https://runningwithproblems.run

# Build settings (only touch this if you know what you are doing)
permalink: /episodes/:slug
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
